# name: Keep Render App Awake

on:
  schedule:
    - cron: "*/5 * * * *" 
  workflow_dispatch:       # Allow manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping your Render App
        run: curl -s https://ronaldon71.github.io/Manipur_tour_management > /dev/null
